import { Product } from "./types";

// Demo data for MVP — will be replaced by Supabase queries
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    merchant_id: "m1",
    title: "Baccarat Rouge 540",
    description: "Maison Francis Kurkdjian — shirin, ambergris va safron hidi. Eng mashhur niche atirlardan biri.",
    price_usd: 35,
    product_type: "lux_copy",
    image_url: "/products/baccarat.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    merchant_id: "m1",
    title: "Tom Ford Lost Cherry",
    description: "Gilos, bodom va turkey rose notalari. Issiq va jozibali atir.",
    price_usd: 40,
    product_type: "lux_copy",
    image_url: "/products/lost-cherry.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    merchant_id: "m1",
    title: "Creed Aventus",
    description: "Ananas, qora smorodina va mesha. Erkaklar uchun eng mashhur atir.",
    price_usd: 38,
    product_type: "lux_copy",
    image_url: "/products/aventus.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    merchant_id: "m1",
    title: "Chanel No. 5",
    description: "Klassik aldegidli guldor kompozitsiya. Dunyodagi eng mashhur ayollar atiri.",
    price_usd: 32,
    product_type: "lux_copy",
    image_url: "/products/chanel5.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    merchant_id: "m1",
    title: "Dior Sauvage",
    description: "Bergamot va Ambroxan — zamonaviy erkaklik atiri. Dunyoda eng ko'p sotilgan erkaklar parfyumi.",
    price_usd: 30,
    product_type: "lux_copy",
    image_url: "/products/sauvage.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    merchant_id: "m1",
    title: "YSL Libre",
    description: "Lavanda va apelsin gulining yoqimli uyg'unligi. Zamonaviy ayol uchun yaratilgan.",
    price_usd: 28,
    product_type: "lux_copy",
    image_url: "/products/libre.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  // Original (Zakaz) perfumes
  {
    id: "7",
    merchant_id: "m1",
    title: "Maison Francis Kurkdjian — Baccarat Rouge 540 (Original)",
    description: "Haqiqiy original. Fransiyadan to'g'ridan-to'g'ri buyurtma qilinadi. 7-14 kunlik yetkazib berish.",
    price_usd: 320,
    product_type: "original",
    image_url: "/products/baccarat-orig.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    merchant_id: "m1",
    title: "Tom Ford Tobacco Vanille (Original)",
    description: "Vanil va tamaki uyg'unligi. Qishki kechalar uchun ideal tanlov. Buyurtma asosida.",
    price_usd: 280,
    product_type: "original",
    image_url: "/products/tobacco-orig.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    merchant_id: "m1",
    title: "Creed Aventus (Original)",
    description: "Erkaklar uchun eng presijli atir. Buyurtma asosida yetkaziladi.",
    price_usd: 350,
    product_type: "original",
    image_url: "/products/aventus-orig.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    merchant_id: "m1",
    title: "Parfums de Marly Layton (Original)",
    description: "Vanil, lavanda va olma notalari. Premium erkaklar parfyumeriyasi.",
    price_usd: 290,
    product_type: "original",
    image_url: "/products/layton-orig.jpg",
    is_available: true,
    created_at: new Date().toISOString(),
  },
];
